name: ROS Build Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros-version: [humble, iron, jazzy]
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.ros-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.ros-version }}
      
      - name: Build docker image
        run: |
          docker buildx build \
            --tag local:${{ matrix.ros-version }} \
            --load \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --file .devcontainer/${{ matrix.ros-version }}/Dockerfile .

      - name: Adjust permissions
        run: |
          docker run -v ${{ github.workspace }}:/workspace -w /workspace local:${{ matrix.ros-version }} \
          sh -c 'username=$(id -un) && sudo chown -R "$username":"$username" /workspace'

      - name: Run colcon build
        run: |
          docker run -v ${{ github.workspace }}:/workspace -w /workspace local:${{ matrix.ros-version }} \
            /bin/bash -c "rosdep install --from-paths odrive_ros2_control odrive_botwheel_explorer -y --ignore-src && \
            colcon build"
